// Code generated by Slice Machine. DO NOT EDIT.

import type * as prismic from "@prismicio/client";

type Simplify<T> = { [KeyType in keyof T]: T[KeyType] };

/**
 * Item in *About Landing → Slideshow*
 */
export interface AboutDocumentDataSlideshowItem {
  /**
   * Image field in *About Landing → Slideshow*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: about.slideshow[].image
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  image: prismic.ImageField<never>;

  /**
   * Vimeo Video Loop field in *About Landing → Slideshow*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: about.slideshow[].vimeo_video_loop
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  vimeo_video_loop: prismic.KeyTextField;
}

/**
 * Item in *About Landing → What We Do*
 */
export interface AboutDocumentDataWhatWeDoItem {
  /**
   * Heading field in *About Landing → What We Do*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: about.what_we_do[].heading
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  heading: prismic.RichTextField;

  /**
   * Paragraph field in *About Landing → What We Do*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: about.what_we_do[].paragraph
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  paragraph: prismic.RichTextField;
}

/**
 * Item in *About Landing → What Slideshow*
 */
export interface AboutDocumentDataWhatSlideshowItem {
  /**
   * Image field in *About Landing → What Slideshow*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: about.what_slideshow[].image
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  image: prismic.ImageField<never>;
}

/**
 * Item in *About Landing → Team List*
 */
export interface AboutDocumentDataTeamListItem {
  /**
   * Image field in *About Landing → Team List*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: about.team_list[].image
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  image: prismic.ImageField<never>;

  /**
   * Name field in *About Landing → Team List*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: about.team_list[].name
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  name: prismic.KeyTextField;

  /**
   * Job Title field in *About Landing → Team List*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: about.team_list[].job_title
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  job_title: prismic.KeyTextField;

  /**
   * Alternative title field in *About Landing → Team List*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: about.team_list[].alternative_title_rich
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  alternative_title_rich: prismic.RichTextField;
}

/**
 * Content for About Landing documents
 */
interface AboutDocumentData {
  /**
   * Page title field in *About Landing*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: about.page_title
   * - **Tab**: SEO
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  page_title: prismic.KeyTextField;

  /**
   * Page description field in *About Landing*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A brief summary of the page
   * - **API ID Path**: about.meta_description
   * - **Tab**: SEO
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  meta_description: prismic.KeyTextField /**
   * heading field in *About Landing*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: about.heading
   * - **Tab**: Introduction
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */;
  heading: prismic.RichTextField;

  /**
   * Sub heading field in *About Landing*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: about.sub_heading
   * - **Tab**: Introduction
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  sub_heading: prismic.RichTextField;

  /**
   * Paragraph field in *About Landing*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: about.paragraph
   * - **Tab**: Introduction
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  paragraph: prismic.RichTextField;

  /**
   * Slideshow field in *About Landing*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: about.slideshow[]
   * - **Tab**: Introduction
   * - **Documentation**: https://prismic.io/docs/field#group
   */
  slideshow: prismic.GroupField<Simplify<AboutDocumentDataSlideshowItem>> /**
   * Why Heading field in *About Landing*
   *
   * - **Field Type**: Title
   * - **Placeholder**: *None*
   * - **API ID Path**: about.why_heading
   * - **Tab**: Why
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */;
  why_heading: prismic.TitleField;

  /**
   * Why Paragraph field in *About Landing*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: about.why_paragraph
   * - **Tab**: Why
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  why_paragraph: prismic.RichTextField /**
   * What Heading field in *About Landing*
   *
   * - **Field Type**: Title
   * - **Placeholder**: *None*
   * - **API ID Path**: about.what_heading
   * - **Tab**: What
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */;
  what_heading: prismic.TitleField;

  /**
   * What We Do field in *About Landing*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: about.what_we_do[]
   * - **Tab**: What
   * - **Documentation**: https://prismic.io/docs/field#group
   */
  what_we_do: prismic.GroupField<Simplify<AboutDocumentDataWhatWeDoItem>>;

  /**
   * What Slideshow field in *About Landing*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: about.what_slideshow[]
   * - **Tab**: What
   * - **Documentation**: https://prismic.io/docs/field#group
   */
  what_slideshow: prismic.GroupField<
    Simplify<AboutDocumentDataWhatSlideshowItem>
  >;

  /**
   * What Slideshow Text field in *About Landing*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: about.what_slideshow_text
   * - **Tab**: What
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  what_slideshow_text: prismic.RichTextField /**
   * Team Heading field in *About Landing*
   *
   * - **Field Type**: Title
   * - **Placeholder**: *None*
   * - **API ID Path**: about.team_heading
   * - **Tab**: Team
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */;
  team_heading: prismic.TitleField;

  /**
   * Team Paragraph field in *About Landing*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: about.team_paragraph
   * - **Tab**: Team
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  team_paragraph: prismic.RichTextField;

  /**
   * Team List field in *About Landing*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: about.team_list[]
   * - **Tab**: Team
   * - **Documentation**: https://prismic.io/docs/field#group
   */
  team_list: prismic.GroupField<Simplify<AboutDocumentDataTeamListItem>> /**
   * Call to action field in *About Landing*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: about.call_to_action
   * - **Tab**: Footer
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */;
  call_to_action: prismic.RichTextField;

  /**
   * Call to action link field in *About Landing*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: about.call_to_action_link
   * - **Tab**: Footer
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  call_to_action_link: prismic.LinkField<
    string,
    string,
    unknown,
    prismic.FieldState,
    never
  >;
}

/**
 * About Landing document from Prismic
 *
 * - **API ID**: `about`
 * - **Repeatable**: `false`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type AboutDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithUID<Simplify<AboutDocumentData>, "about", Lang>;

/**
 * Item in *Archive Landing → Projects*
 */
export interface ArchiveDocumentDataProjectsItem {
  /**
   * Case study field in *Archive Landing → Projects*
   *
   * - **Field Type**: Content Relationship
   * - **Placeholder**: *None*
   * - **API ID Path**: archive.projects[].case_study
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  case_study: prismic.ContentRelationshipField<"case_study">;
}

/**
 * Content for Archive Landing documents
 */
interface ArchiveDocumentData {
  /**
   * Page title field in *Archive Landing*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: archive.page_title
   * - **Tab**: SEO
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  page_title: prismic.KeyTextField;

  /**
   * Page description field in *Archive Landing*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A brief summary of the page
   * - **API ID Path**: archive.meta_description
   * - **Tab**: SEO
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  meta_description: prismic.KeyTextField /**
   * Projects field in *Archive Landing*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: archive.projects[]
   * - **Tab**: Projects
   * - **Documentation**: https://prismic.io/docs/field#group
   */;
  projects: prismic.GroupField<Simplify<ArchiveDocumentDataProjectsItem>> /**
   * Call to action field in *Archive Landing*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: archive.call_to_action
   * - **Tab**: Footer
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */;
  call_to_action: prismic.RichTextField;
}

/**
 * Archive Landing document from Prismic
 *
 * - **API ID**: `archive`
 * - **Repeatable**: `false`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type ArchiveDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithUID<
    Simplify<ArchiveDocumentData>,
    "archive",
    Lang
  >;

/**
 * Item in *Case Study → Gallery Thumbnail*
 */
export interface CaseStudyDocumentDataGalleryThumbnailItem {
  /**
   * Image field in *Case Study → Gallery Thumbnail*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: case_study.gallery_thumbnail[].image
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  image: prismic.ImageField<never>;
}

/**
 * Item in *Case Study → Client*
 */
export interface CaseStudyDocumentDataClientItem {
  /**
   * Client field in *Case Study → Client*
   *
   * - **Field Type**: Content Relationship
   * - **Placeholder**: *None*
   * - **API ID Path**: case_study.client[].client
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  client: prismic.ContentRelationshipField<"client">;
}

/**
 * Item in *Case Study → Industry*
 */
export interface CaseStudyDocumentDataIndustryItem {
  /**
   * Industry field in *Case Study → Industry*
   *
   * - **Field Type**: Content Relationship
   * - **Placeholder**: *None*
   * - **API ID Path**: case_study.industry[].industry
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  industry: prismic.ContentRelationshipField<"industry">;
}

type CaseStudyDocumentDataSlices4Slice =
  | DoubleMediaSlice
  | AudioPlayerSlice
  | TextSliceSlice
  | VideoPlayerSlice
  | SmallMediaSlice
  | SmallGallerySlice
  | LargeMediaSlice
  | MediumMediaSlice;

/**
 * Content for Case Study documents
 */
interface CaseStudyDocumentData {
  /**
   * Page title field in *Case Study*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: case_study.page_title
   * - **Tab**: SEO
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  page_title: prismic.KeyTextField;

  /**
   * Page description field in *Case Study*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A brief summary of the page
   * - **API ID Path**: case_study.meta_description
   * - **Tab**: SEO
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  meta_description: prismic.KeyTextField /**
   * Image Thumbnail field in *Case Study*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: case_study.image_thumbnail
   * - **Tab**: Thumbnail
   * - **Documentation**: https://prismic.io/docs/field#image
   */;
  image_thumbnail: prismic.ImageField<"Square">;

  /**
   * Vimeo Loop Thumbnail field in *Case Study*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: case_study.vimeo_loop_thumbnail
   * - **Tab**: Thumbnail
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  vimeo_loop_thumbnail: prismic.KeyTextField;

  /**
   * Gallery Thumbnail field in *Case Study*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: case_study.gallery_thumbnail[]
   * - **Tab**: Thumbnail
   * - **Documentation**: https://prismic.io/docs/field#group
   */
  gallery_thumbnail: prismic.GroupField<
    Simplify<CaseStudyDocumentDataGalleryThumbnailItem>
  >;

  /**
   * Thumbnail Title field in *Case Study*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: case_study.thumbnail_title
   * - **Tab**: Thumbnail
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  thumbnail_title: prismic.RichTextField /**
   * Header Image field in *Case Study*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: case_study.header_image
   * - **Tab**: Header
   * - **Documentation**: https://prismic.io/docs/field#image
   */;
  header_image: prismic.ImageField<never>;

  /**
   * Header Vimeo Video Link field in *Case Study*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: case_study.header_vimeo_video_link
   * - **Tab**: Header
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  header_vimeo_video_link: prismic.KeyTextField;

  /**
   * Header Paragraph field in *Case Study*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: case_study.header_paragraph
   * - **Tab**: Header
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  header_paragraph: prismic.RichTextField /**
   * Client field in *Case Study*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: case_study.client[]
   * - **Tab**: Meta
   * - **Documentation**: https://prismic.io/docs/field#group
   */;
  client: prismic.GroupField<Simplify<CaseStudyDocumentDataClientItem>>;

  /**
   * Industry field in *Case Study*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: case_study.industry[]
   * - **Tab**: Meta
   * - **Documentation**: https://prismic.io/docs/field#group
   */
  industry: prismic.GroupField<Simplify<CaseStudyDocumentDataIndustryItem>>;

  /**
   * Scope field in *Case Study*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: case_study.scope
   * - **Tab**: Meta
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  scope: prismic.RichTextField;

  /**
   * Year field in *Case Study*
   *
   * - **Field Type**: Number
   * - **Placeholder**: *None*
   * - **API ID Path**: case_study.year
   * - **Tab**: Meta
   * - **Documentation**: https://prismic.io/docs/field#number
   */
  year: prismic.NumberField;

  /**
   * External Link field in *Case Study*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: case_study.link
   * - **Tab**: Meta
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  link: prismic.LinkField<
    string,
    string,
    unknown,
    prismic.FieldState,
    never
  > /**
   * Information field in *Case Study*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: case_study.information
   * - **Tab**: Content
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */;
  information: prismic.RichTextField;

  /**
   * Quote field in *Case Study*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: case_study.quote
   * - **Tab**: Content
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  quote: prismic.RichTextField;

  /**
   * Quote Cite field in *Case Study*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: case_study.quote_cite
   * - **Tab**: Content
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  quote_cite: prismic.RichTextField;

  /**
   * Slice Zone field in *Case Study*
   *
   * - **Field Type**: Slice Zone
   * - **Placeholder**: *None*
   * - **API ID Path**: case_study.slices4[]
   * - **Tab**: Content
   * - **Documentation**: https://prismic.io/docs/field#slices
   */
  slices4: prismic.SliceZone<CaseStudyDocumentDataSlices4Slice> /**
   * Archived field in *Case Study*
   *
   * - **Field Type**: Boolean
   * - **Placeholder**: *None*
   * - **Default Value**: false
   * - **API ID Path**: case_study.archived
   * - **Tab**: Status
   * - **Documentation**: https://prismic.io/docs/field#boolean
   */;
  archived: prismic.BooleanField /**
   * Call to action field in *Case Study*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: case_study.call_to_action
   * - **Tab**: Footer
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */;
  call_to_action: prismic.RichTextField;

  /**
   * Call to action link field in *Case Study*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: case_study.call_to_action_link
   * - **Tab**: Footer
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  call_to_action_link: prismic.LinkField<
    string,
    string,
    unknown,
    prismic.FieldState,
    never
  >;
}

/**
 * Case Study document from Prismic
 *
 * - **API ID**: `case_study`
 * - **Repeatable**: `true`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type CaseStudyDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithUID<
    Simplify<CaseStudyDocumentData>,
    "case_study",
    Lang
  >;

/**
 * Content for Client documents
 */
interface ClientDocumentData {
  /**
   * Client Name field in *Client*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: client.client_name
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  client_name: prismic.KeyTextField;
}

/**
 * Client document from Prismic
 *
 * - **API ID**: `client`
 * - **Repeatable**: `true`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type ClientDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithUID<Simplify<ClientDocumentData>, "client", Lang>;

/**
 * Content for Contact documents
 */
interface ContactDocumentData {
  /**
   * Page title field in *Contact*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: contact.page_title
   * - **Tab**: SEO
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  page_title: prismic.KeyTextField;

  /**
   * Page description field in *Contact*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A brief summary of the page
   * - **API ID Path**: contact.meta_description
   * - **Tab**: SEO
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  meta_description: prismic.KeyTextField;
}

/**
 * Contact document from Prismic
 *
 * - **API ID**: `contact`
 * - **Repeatable**: `false`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type ContactDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithUID<
    Simplify<ContactDocumentData>,
    "contact",
    Lang
  >;

/**
 * Content for Global documents
 */
interface GlobalDocumentData {
  /**
   * Phone field in *Global*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: global.phone
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  phone: prismic.LinkField<string, string, unknown, prismic.FieldState, never>;

  /**
   * Email field in *Global*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: global.email
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  email: prismic.LinkField<string, string, unknown, prismic.FieldState, never>;

  /**
   * Instagram field in *Global*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: global.instagram
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  instagram: prismic.LinkField<
    string,
    string,
    unknown,
    prismic.FieldState,
    never
  >;

  /**
   * Linkedin field in *Global*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: global.linkedin
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  linkedin: prismic.LinkField<
    string,
    string,
    unknown,
    prismic.FieldState,
    never
  >;

  /**
   * Address field in *Global*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: global.address
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  address: prismic.RichTextField;
}

/**
 * Global document from Prismic
 *
 * - **API ID**: `global`
 * - **Repeatable**: `false`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type GlobalDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithoutUID<
    Simplify<GlobalDocumentData>,
    "global",
    Lang
  >;

/**
 * Item in *Home → Slideshow*
 */
export interface HomeDocumentDataSlideshowItem {
  /**
   * Image field in *Home → Slideshow*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: home.slideshow[].image
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  image: prismic.ImageField<never>;

  /**
   * Video Loop field in *Home → Slideshow*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: home.slideshow[].video
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  video: prismic.LinkField<string, string, unknown, prismic.FieldState, never>;

  /**
   * Caption field in *Home → Slideshow*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: home.slideshow[].caption
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  caption: prismic.RichTextField;

  /**
   * Link field in *Home → Slideshow*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: home.slideshow[].link
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  link: prismic.LinkField<string, string, unknown, prismic.FieldState, never>;
}

type HomeDocumentDataSlices2Slice = ProjectSlice;

/**
 * Item in *Home → News slideshow*
 */
export interface HomeDocumentDataAboutSlideshowItem {
  /**
   * Image field in *Home → News slideshow*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: home.about_slideshow[].image
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  image: prismic.ImageField<never>;
}

/**
 * Content for Home documents
 */
interface HomeDocumentData {
  /**
   * Page title field in *Home*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: home.page_title
   * - **Tab**: SEO
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  page_title: prismic.KeyTextField;

  /**
   * Page description field in *Home*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A brief summary of the page
   * - **API ID Path**: home.meta_description
   * - **Tab**: SEO
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  meta_description: prismic.KeyTextField /**
   * Slideshow field in *Home*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: home.slideshow[]
   * - **Tab**: Slideshow
   * - **Documentation**: https://prismic.io/docs/field#group
   */;
  slideshow: prismic.GroupField<Simplify<HomeDocumentDataSlideshowItem>> /**
   * Introduction field in *Home*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: home.introduction
   * - **Tab**: Projects
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */;
  introduction: prismic.RichTextField;

  /**
   * Slice Zone field in *Home*
   *
   * - **Field Type**: Slice Zone
   * - **Placeholder**: *None*
   * - **API ID Path**: home.slices2[]
   * - **Tab**: Projects
   * - **Documentation**: https://prismic.io/docs/field#slices
   */
  slices2: prismic.SliceZone<HomeDocumentDataSlices2Slice> /**
   * About Copy field in *Home*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: home.about_copy
   * - **Tab**: About
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */;
  about_copy: prismic.RichTextField;

  /**
   * About Link field in *Home*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: home.about_link
   * - **Tab**: About
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  about_link: prismic.LinkField<
    string,
    string,
    unknown,
    prismic.FieldState,
    never
  >;

  /**
   * News slideshow field in *Home*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: home.about_slideshow[]
   * - **Tab**: About
   * - **Documentation**: https://prismic.io/docs/field#group
   */
  about_slideshow: prismic.GroupField<
    Simplify<HomeDocumentDataAboutSlideshowItem>
  >;

  /**
   * News Link field in *Home*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: home.news_link
   * - **Tab**: About
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  news_link: prismic.LinkField<
    string,
    string,
    unknown,
    prismic.FieldState,
    never
  > /**
   * Call to action field in *Home*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: home.call_to_action
   * - **Tab**: Footer
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */;
  call_to_action: prismic.RichTextField;

  /**
   * Call to action link field in *Home*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: home.call_to_action_link
   * - **Tab**: Footer
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  call_to_action_link: prismic.LinkField<
    string,
    string,
    unknown,
    prismic.FieldState,
    never
  >;
}

/**
 * Home document from Prismic
 *
 * - **API ID**: `home`
 * - **Repeatable**: `false`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type HomeDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithUID<Simplify<HomeDocumentData>, "home", Lang>;

/**
 * Content for Industry documents
 */
interface IndustryDocumentData {
  /**
   * Industry Name field in *Industry*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: industry.industry_name
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  industry_name: prismic.KeyTextField;
}

/**
 * Industry document from Prismic
 *
 * - **API ID**: `industry`
 * - **Repeatable**: `true`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type IndustryDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithUID<
    Simplify<IndustryDocumentData>,
    "industry",
    Lang
  >;

/**
 * Item in *Main Menu → Links*
 */
export interface MainMenuDocumentDataLinksItem {
  /**
   * Link field in *Main Menu → Links*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: main_menu.links[].link
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  link: prismic.LinkField<string, string, unknown, prismic.FieldState, never>;
}

/**
 * Content for Main Menu documents
 */
interface MainMenuDocumentData {
  /**
   * Links field in *Main Menu*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: main_menu.links[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#group
   */
  links: prismic.GroupField<Simplify<MainMenuDocumentDataLinksItem>>;
}

/**
 * Main Menu document from Prismic
 *
 * - **API ID**: `main_menu`
 * - **Repeatable**: `false`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type MainMenuDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithoutUID<
    Simplify<MainMenuDocumentData>,
    "main_menu",
    Lang
  >;

/**
 * Item in *Mobile Menu → Links*
 */
export interface MobileMenuDocumentDataLinksItem {
  /**
   * Link field in *Mobile Menu → Links*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: mobile_menu.links[].link
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  link: prismic.LinkField<string, string, unknown, prismic.FieldState, never>;
}

/**
 * Content for Mobile Menu documents
 */
interface MobileMenuDocumentData {
  /**
   * Links field in *Mobile Menu*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: mobile_menu.links[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#group
   */
  links: prismic.GroupField<Simplify<MobileMenuDocumentDataLinksItem>>;
}

/**
 * Mobile Menu document from Prismic
 *
 * - **API ID**: `mobile_menu`
 * - **Repeatable**: `false`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type MobileMenuDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithoutUID<
    Simplify<MobileMenuDocumentData>,
    "mobile_menu",
    Lang
  >;

/**
 * Content for News Item documents
 */
interface NewsDocumentData {
  /**
   * Page title field in *News Item*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: news.page_title
   * - **Tab**: SEO
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  page_title: prismic.KeyTextField;

  /**
   * Page description field in *News Item*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A brief summary of the page
   * - **API ID Path**: news.meta_description
   * - **Tab**: SEO
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  meta_description: prismic.KeyTextField /**
   * Image Thumbnail field in *News Item*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: news.image_thumbnail
   * - **Tab**: Thumbnail
   * - **Documentation**: https://prismic.io/docs/field#image
   */;
  image_thumbnail: prismic.ImageField<never>;

  /**
   * Vimeo Loop field in *News Item*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: news.video_thumbnail
   * - **Tab**: Thumbnail
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  video_thumbnail: prismic.KeyTextField /**
   * Heading field in *News Item*
   *
   * - **Field Type**: Title
   * - **Placeholder**: *None*
   * - **API ID Path**: news.heading
   * - **Tab**: Content
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */;
  heading: prismic.TitleField;

  /**
   * Paragraph field in *News Item*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: news.paragraph
   * - **Tab**: Content
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  paragraph: prismic.RichTextField;

  /**
   * Link field in *News Item*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: news.link
   * - **Tab**: Content
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  link: prismic.LinkField<string, string, unknown, prismic.FieldState, never>;
}

/**
 * News Item document from Prismic
 *
 * - **API ID**: `news`
 * - **Repeatable**: `true`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type NewsDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithUID<Simplify<NewsDocumentData>, "news", Lang>;

/**
 * Item in *News Landing → News items*
 */
export interface NewsLandingDocumentDataNewsItemsItem {
  /**
   * Item field in *News Landing → News items*
   *
   * - **Field Type**: Content Relationship
   * - **Placeholder**: *None*
   * - **API ID Path**: news_landing.news_items[].item
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  item: prismic.ContentRelationshipField<"news">;
}

/**
 * Content for News Landing documents
 */
interface NewsLandingDocumentData {
  /**
   * Page title field in *News Landing*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: news_landing.page_title
   * - **Tab**: SEO
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  page_title: prismic.KeyTextField;

  /**
   * Page description field in *News Landing*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A brief summary of the page
   * - **API ID Path**: news_landing.meta_description
   * - **Tab**: SEO
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  meta_description: prismic.KeyTextField /**
   * heading field in *News Landing*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: news_landing.heading
   * - **Tab**: Introduction
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */;
  heading: prismic.RichTextField;

  /**
   * Sub heading field in *News Landing*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: news_landing.sub_heading
   * - **Tab**: Introduction
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  sub_heading: prismic.RichTextField /**
   * News items field in *News Landing*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: news_landing.news_items[]
   * - **Tab**: Content
   * - **Documentation**: https://prismic.io/docs/field#group
   */;
  news_items: prismic.GroupField<
    Simplify<NewsLandingDocumentDataNewsItemsItem>
  >;
}

/**
 * News Landing document from Prismic
 *
 * - **API ID**: `news_landing`
 * - **Repeatable**: `false`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type NewsLandingDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithUID<
    Simplify<NewsLandingDocumentData>,
    "news_landing",
    Lang
  >;

/**
 * Item in *Work Landing → Projects*
 */
export interface WorkDocumentDataProjectsItem {
  /**
   * Case study field in *Work Landing → Projects*
   *
   * - **Field Type**: Content Relationship
   * - **Placeholder**: *None*
   * - **API ID Path**: work.projects[].case_study
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  case_study: prismic.ContentRelationshipField<"case_study">;
}

/**
 * Content for Work Landing documents
 */
interface WorkDocumentData {
  /**
   * Page title field in *Work Landing*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: work.page_title
   * - **Tab**: SEO
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  page_title: prismic.KeyTextField;

  /**
   * Page description field in *Work Landing*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A brief summary of the page
   * - **API ID Path**: work.meta_description
   * - **Tab**: SEO
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  meta_description: prismic.KeyTextField /**
   * heading field in *Work Landing*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: work.heading
   * - **Tab**: Introduction
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */;
  heading: prismic.RichTextField;

  /**
   * Sub heading field in *Work Landing*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: work.sub_heading
   * - **Tab**: Introduction
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  sub_heading: prismic.RichTextField;

  /**
   * Paragraph field in *Work Landing*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: work.paragraph
   * - **Tab**: Introduction
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  paragraph: prismic.RichTextField /**
   * Projects field in *Work Landing*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: work.projects[]
   * - **Tab**: Projects
   * - **Documentation**: https://prismic.io/docs/field#group
   */;
  projects: prismic.GroupField<Simplify<WorkDocumentDataProjectsItem>> /**
   * Call to action field in *Work Landing*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: work.call_to_action
   * - **Tab**: Footer
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */;
  call_to_action: prismic.RichTextField;
}

/**
 * Work Landing document from Prismic
 *
 * - **API ID**: `work`
 * - **Repeatable**: `false`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type WorkDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithUID<Simplify<WorkDocumentData>, "work", Lang>;

export type AllDocumentTypes =
  | AboutDocument
  | ArchiveDocument
  | CaseStudyDocument
  | ClientDocument
  | ContactDocument
  | GlobalDocument
  | HomeDocument
  | IndustryDocument
  | MainMenuDocument
  | MobileMenuDocument
  | NewsDocument
  | NewsLandingDocument
  | WorkDocument;

/**
 * Primary content in *AudioPlayer → Default → Primary*
 */
export interface AudioPlayerSliceDefaultPrimary {
  /**
   * Audio Title field in *AudioPlayer → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: audio_player.default.primary.audio_title
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  audio_title: prismic.RichTextField;

  /**
   * Audio File (MP3) field in *AudioPlayer → Default → Primary*
   *
   * - **Field Type**: Link to Media
   * - **Placeholder**: *None*
   * - **API ID Path**: audio_player.default.primary.audio_file
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  audio_file: prismic.LinkToMediaField<prismic.FieldState, never>;
}

/**
 * Default variation for AudioPlayer Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type AudioPlayerSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<AudioPlayerSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *AudioPlayer*
 */
type AudioPlayerSliceVariation = AudioPlayerSliceDefault;

/**
 * AudioPlayer Shared Slice
 *
 * - **API ID**: `audio_player`
 * - **Description**: AudioPlayer
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type AudioPlayerSlice = prismic.SharedSlice<
  "audio_player",
  AudioPlayerSliceVariation
>;

/**
 * Primary content in *DoubleMedia → Default → Primary*
 */
export interface DoubleMediaSliceDefaultPrimary {
  /**
   * Left Image field in *DoubleMedia → Default → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: double_media.default.primary.left_image
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  left_image: prismic.ImageField<never>;

  /**
   * Left Vimeo Video Link field in *DoubleMedia → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: double_media.default.primary.left_vimeo_video_link
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  left_vimeo_video_link: prismic.KeyTextField;

  /**
   * Left caption field in *DoubleMedia → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: double_media.default.primary.left_caption
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  left_caption: prismic.RichTextField;

  /**
   * Right Image field in *DoubleMedia → Default → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: double_media.default.primary.right_image
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  right_image: prismic.ImageField<never>;

  /**
   * Right Vimeo Video Link field in *DoubleMedia → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: double_media.default.primary.right_vimeo_video_link
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  right_vimeo_video_link: prismic.KeyTextField;

  /**
   * Bottom Margin field in *DoubleMedia → Default → Primary*
   *
   * - **Field Type**: Boolean
   * - **Placeholder**: *None*
   * - **Default Value**: false
   * - **API ID Path**: double_media.default.primary.bottom_margin
   * - **Documentation**: https://prismic.io/docs/field#boolean
   */
  bottom_margin: prismic.BooleanField;

  /**
   * Align media field in *DoubleMedia → Default → Primary*
   *
   * - **Field Type**: Select
   * - **Placeholder**: *None*
   * - **API ID Path**: double_media.default.primary.align_media
   * - **Documentation**: https://prismic.io/docs/field#select
   */
  align_media: prismic.SelectField<
    "Align left" | "Align center" | "Align right"
  >;

  /**
   * Right Caption field in *DoubleMedia → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: double_media.default.primary.right_caption
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  right_caption: prismic.RichTextField;
}

/**
 * Default variation for DoubleMedia Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type DoubleMediaSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<DoubleMediaSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *DoubleMedia*
 */
type DoubleMediaSliceVariation = DoubleMediaSliceDefault;

/**
 * DoubleMedia Shared Slice
 *
 * - **API ID**: `double_media`
 * - **Description**: DoubleMedia
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type DoubleMediaSlice = prismic.SharedSlice<
  "double_media",
  DoubleMediaSliceVariation
>;

/**
 * Primary content in *LargeMedia → Image → Primary*
 */
export interface LargeMediaSliceDefaultPrimary {
  /**
   * Image field in *LargeMedia → Image → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: large_media.default.primary.image
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  image: prismic.ImageField<never>;

  /**
   * Bottom Margin field in *LargeMedia → Image → Primary*
   *
   * - **Field Type**: Boolean
   * - **Placeholder**: *None*
   * - **Default Value**: false
   * - **API ID Path**: large_media.default.primary.bottom_margin
   * - **Documentation**: https://prismic.io/docs/field#boolean
   */
  bottom_margin: prismic.BooleanField;
}

/**
 * Image variation for LargeMedia Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type LargeMediaSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<LargeMediaSliceDefaultPrimary>,
  never
>;

/**
 * Primary content in *LargeMedia → Video Loop → Primary*
 */
export interface LargeMediaSliceVideoPrimary {
  /**
   * Video Placeholder Image field in *LargeMedia → Video Loop → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: large_media.video.primary.video_placeholder_image
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  video_placeholder_image: prismic.ImageField<never>;

  /**
   * Vimeo Video Link field in *LargeMedia → Video Loop → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: large_media.video.primary.vimeo_video_link_new
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  vimeo_video_link_new: prismic.KeyTextField;

  /**
   * Bottom Margin field in *LargeMedia → Video Loop → Primary*
   *
   * - **Field Type**: Boolean
   * - **Placeholder**: *None*
   * - **Default Value**: false
   * - **API ID Path**: large_media.video.primary.bottom_margin
   * - **Documentation**: https://prismic.io/docs/field#boolean
   */
  bottom_margin: prismic.BooleanField;
}

/**
 * Video Loop variation for LargeMedia Slice
 *
 * - **API ID**: `video`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type LargeMediaSliceVideo = prismic.SharedSliceVariation<
  "video",
  Simplify<LargeMediaSliceVideoPrimary>,
  never
>;

/**
 * Slice variation for *LargeMedia*
 */
type LargeMediaSliceVariation = LargeMediaSliceDefault | LargeMediaSliceVideo;

/**
 * LargeMedia Shared Slice
 *
 * - **API ID**: `large_media`
 * - **Description**: LargeMedia
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type LargeMediaSlice = prismic.SharedSlice<
  "large_media",
  LargeMediaSliceVariation
>;

/**
 * Primary content in *MediumMedia → Image → Primary*
 */
export interface MediumMediaSliceDefaultPrimary {
  /**
   * Image field in *MediumMedia → Image → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: medium_media.default.primary.image
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  image: prismic.ImageField<never>;

  /**
   * Bottom Margin field in *MediumMedia → Image → Primary*
   *
   * - **Field Type**: Boolean
   * - **Placeholder**: *None*
   * - **Default Value**: false
   * - **API ID Path**: medium_media.default.primary.bottom_margin
   * - **Documentation**: https://prismic.io/docs/field#boolean
   */
  bottom_margin: prismic.BooleanField;

  /**
   * Align Media field in *MediumMedia → Image → Primary*
   *
   * - **Field Type**: Select
   * - **Placeholder**: *None*
   * - **Default Value**: Align left
   * - **API ID Path**: medium_media.default.primary.align_media
   * - **Documentation**: https://prismic.io/docs/field#select
   */
  align_media: prismic.SelectField<
    "Align left" | "Align center" | "Align right",
    "filled"
  >;
}

/**
 * Image variation for MediumMedia Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type MediumMediaSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<MediumMediaSliceDefaultPrimary>,
  never
>;

/**
 * Primary content in *MediumMedia → Video Loop → Primary*
 */
export interface MediumMediaSliceVideoPrimary {
  /**
   * Image field in *MediumMedia → Video Loop → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: medium_media.video.primary.image
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  image: prismic.ImageField<never>;

  /**
   * Vimeo Video Link field in *MediumMedia → Video Loop → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: medium_media.video.primary.vimeo_video_link_new
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  vimeo_video_link_new: prismic.KeyTextField;

  /**
   * Bottom Margin field in *MediumMedia → Video Loop → Primary*
   *
   * - **Field Type**: Boolean
   * - **Placeholder**: *None*
   * - **Default Value**: false
   * - **API ID Path**: medium_media.video.primary.bottom_margin
   * - **Documentation**: https://prismic.io/docs/field#boolean
   */
  bottom_margin: prismic.BooleanField;

  /**
   * Align media field in *MediumMedia → Video Loop → Primary*
   *
   * - **Field Type**: Select
   * - **Placeholder**: *None*
   * - **Default Value**: Align left
   * - **API ID Path**: medium_media.video.primary.align_media
   * - **Documentation**: https://prismic.io/docs/field#select
   */
  align_media: prismic.SelectField<
    "Align left" | "Align center" | "Align right",
    "filled"
  >;
}

/**
 * Video Loop variation for MediumMedia Slice
 *
 * - **API ID**: `video`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type MediumMediaSliceVideo = prismic.SharedSliceVariation<
  "video",
  Simplify<MediumMediaSliceVideoPrimary>,
  never
>;

/**
 * Slice variation for *MediumMedia*
 */
type MediumMediaSliceVariation =
  | MediumMediaSliceDefault
  | MediumMediaSliceVideo;

/**
 * MediumMedia Shared Slice
 *
 * - **API ID**: `medium_media`
 * - **Description**: MediumMedia
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type MediumMediaSlice = prismic.SharedSlice<
  "medium_media",
  MediumMediaSliceVariation
>;

/**
 * Item in *Project → Default → Primary → Media 1*
 */
export interface ProjectSliceDefaultPrimaryMedia1Item {
  /**
   * Image / Video Placeholder field in *Project → Default → Primary → Media 1*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: project.default.primary.media_1[].image
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  image: prismic.ImageField<never>;

  /**
   * Vimeo Video Link field in *Project → Default → Primary → Media 1*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: project.default.primary.media_1[].vimeo_video_link
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  vimeo_video_link: prismic.LinkField<
    string,
    string,
    unknown,
    prismic.FieldState,
    never
  >;

  /**
   * Enable Parallax field in *Project → Default → Primary → Media 1*
   *
   * - **Field Type**: Boolean
   * - **Placeholder**: *None*
   * - **Default Value**: false
   * - **API ID Path**: project.default.primary.media_1[].parallax_enabled
   * - **Documentation**: https://prismic.io/docs/field#boolean
   */
  parallax_enabled: prismic.BooleanField;
}

/**
 * Item in *Project → Default → Primary → Media 2*
 */
export interface ProjectSliceDefaultPrimaryMedia2Item {
  /**
   * Image / Video Placeholder field in *Project → Default → Primary → Media 2*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: project.default.primary.media_2[].image
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  image: prismic.ImageField<never>;

  /**
   * Vimeo Video Link field in *Project → Default → Primary → Media 2*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: project.default.primary.media_2[].vimeo_video_link
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  vimeo_video_link: prismic.LinkField<
    string,
    string,
    unknown,
    prismic.FieldState,
    never
  >;

  /**
   * Enable Parallax field in *Project → Default → Primary → Media 2*
   *
   * - **Field Type**: Boolean
   * - **Placeholder**: *None*
   * - **Default Value**: false
   * - **API ID Path**: project.default.primary.media_2[].parallax_enabled
   * - **Documentation**: https://prismic.io/docs/field#boolean
   */
  parallax_enabled: prismic.BooleanField;
}

/**
 * Item in *Project → Default → Primary → Media 3*
 */
export interface ProjectSliceDefaultPrimaryMedia3Item {
  /**
   * Image / Video Placeholder field in *Project → Default → Primary → Media 3*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: project.default.primary.media_3[].image
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  image: prismic.ImageField<never>;

  /**
   * Vimeo Video Link field in *Project → Default → Primary → Media 3*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: project.default.primary.media_3[].vimeo_video_link
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  vimeo_video_link: prismic.LinkField<
    string,
    string,
    unknown,
    prismic.FieldState,
    never
  >;

  /**
   * Enable Parallax field in *Project → Default → Primary → Media 3*
   *
   * - **Field Type**: Boolean
   * - **Placeholder**: *None*
   * - **Default Value**: false
   * - **API ID Path**: project.default.primary.media_3[].parallax_enabled
   * - **Documentation**: https://prismic.io/docs/field#boolean
   */
  parallax_enabled: prismic.BooleanField;
}

/**
 * Primary content in *Project → Default → Primary*
 */
export interface ProjectSliceDefaultPrimary {
  /**
   * Project Link field in *Project → Default → Primary*
   *
   * - **Field Type**: Content Relationship
   * - **Placeholder**: *None*
   * - **API ID Path**: project.default.primary.project_link
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  project_link: prismic.ContentRelationshipField<"case_study">;

  /**
   * Project Copy field in *Project → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: project.default.primary.project_copy
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  project_copy: prismic.RichTextField;

  /**
   * Media 1 field in *Project → Default → Primary*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: project.default.primary.media_1[]
   * - **Documentation**: https://prismic.io/docs/field#group
   */
  media_1: prismic.GroupField<Simplify<ProjectSliceDefaultPrimaryMedia1Item>>;

  /**
   * Media 2 field in *Project → Default → Primary*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: project.default.primary.media_2[]
   * - **Documentation**: https://prismic.io/docs/field#group
   */
  media_2: prismic.GroupField<Simplify<ProjectSliceDefaultPrimaryMedia2Item>>;

  /**
   * Media 3 field in *Project → Default → Primary*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: project.default.primary.media_3[]
   * - **Documentation**: https://prismic.io/docs/field#group
   */
  media_3: prismic.GroupField<Simplify<ProjectSliceDefaultPrimaryMedia3Item>>;
}

/**
 * Default variation for Project Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type ProjectSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<ProjectSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *Project*
 */
type ProjectSliceVariation = ProjectSliceDefault;

/**
 * Project Shared Slice
 *
 * - **API ID**: `project`
 * - **Description**: Project
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type ProjectSlice = prismic.SharedSlice<
  "project",
  ProjectSliceVariation
>;

/**
 * Item in *SmallGallery → Default → Primary → Images*
 */
export interface SmallGallerySliceDefaultPrimaryImagesItem {
  /**
   * Image field in *SmallGallery → Default → Primary → Images*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: small_gallery.default.primary.images[].image
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  image: prismic.ImageField<never>;
}

/**
 * Primary content in *SmallGallery → Default → Primary*
 */
export interface SmallGallerySliceDefaultPrimary {
  /**
   * Images field in *SmallGallery → Default → Primary*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: small_gallery.default.primary.images[]
   * - **Documentation**: https://prismic.io/docs/field#group
   */
  images: prismic.GroupField<
    Simplify<SmallGallerySliceDefaultPrimaryImagesItem>
  >;

  /**
   * Align Gallery field in *SmallGallery → Default → Primary*
   *
   * - **Field Type**: Select
   * - **Placeholder**: *None*
   * - **API ID Path**: small_gallery.default.primary.align_gallery
   * - **Documentation**: https://prismic.io/docs/field#select
   */
  align_gallery: prismic.SelectField<
    "Align left" | "Align center" | "Align right"
  >;

  /**
   * Bottom Margin field in *SmallGallery → Default → Primary*
   *
   * - **Field Type**: Boolean
   * - **Placeholder**: *None*
   * - **Default Value**: false
   * - **API ID Path**: small_gallery.default.primary.bottom_margin
   * - **Documentation**: https://prismic.io/docs/field#boolean
   */
  bottom_margin: prismic.BooleanField;
}

/**
 * Default variation for SmallGallery Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type SmallGallerySliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<SmallGallerySliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *SmallGallery*
 */
type SmallGallerySliceVariation = SmallGallerySliceDefault;

/**
 * SmallGallery Shared Slice
 *
 * - **API ID**: `small_gallery`
 * - **Description**: SmallGallery
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type SmallGallerySlice = prismic.SharedSlice<
  "small_gallery",
  SmallGallerySliceVariation
>;

/**
 * Primary content in *SmallMedia → Image → Primary*
 */
export interface SmallMediaSliceDefaultPrimary {
  /**
   * Image field in *SmallMedia → Image → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: small_media.default.primary.image
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  image: prismic.ImageField<never>;

  /**
   * Align Image field in *SmallMedia → Image → Primary*
   *
   * - **Field Type**: Select
   * - **Placeholder**: *None*
   * - **API ID Path**: small_media.default.primary.align_image
   * - **Documentation**: https://prismic.io/docs/field#select
   */
  align_image: prismic.SelectField<
    "Align left" | "Align center" | "Align right"
  >;

  /**
   * Margin Bottom field in *SmallMedia → Image → Primary*
   *
   * - **Field Type**: Boolean
   * - **Placeholder**: *None*
   * - **Default Value**: false
   * - **API ID Path**: small_media.default.primary.margin_bottom
   * - **Documentation**: https://prismic.io/docs/field#boolean
   */
  margin_bottom: prismic.BooleanField;
}

/**
 * Image variation for SmallMedia Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type SmallMediaSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<SmallMediaSliceDefaultPrimary>,
  never
>;

/**
 * Primary content in *SmallMedia → Video loop → Primary*
 */
export interface SmallMediaSliceVideoLoopPrimary {
  /**
   * Video Placeholder Image field in *SmallMedia → Video loop → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: small_media.videoLoop.primary.image
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  image: prismic.ImageField<never>;

  /**
   * Vimeo Video Link field in *SmallMedia → Video loop → Primary*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: small_media.videoLoop.primary.vimeo_video_link
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  vimeo_video_link: prismic.LinkField<
    string,
    string,
    unknown,
    prismic.FieldState,
    never
  >;

  /**
   * Vimeo Video Link field in *SmallMedia → Video loop → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: small_media.videoLoop.primary.vimeo_video_link_new
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  vimeo_video_link_new: prismic.KeyTextField;

  /**
   * Align Video field in *SmallMedia → Video loop → Primary*
   *
   * - **Field Type**: Select
   * - **Placeholder**: *None*
   * - **API ID Path**: small_media.videoLoop.primary.align_image
   * - **Documentation**: https://prismic.io/docs/field#select
   */
  align_image: prismic.SelectField<
    "Align left" | "Align center" | "Align right"
  >;

  /**
   * Margin Bottom field in *SmallMedia → Video loop → Primary*
   *
   * - **Field Type**: Boolean
   * - **Placeholder**: *None*
   * - **Default Value**: false
   * - **API ID Path**: small_media.videoLoop.primary.margin_bottom
   * - **Documentation**: https://prismic.io/docs/field#boolean
   */
  margin_bottom: prismic.BooleanField;
}

/**
 * Video loop variation for SmallMedia Slice
 *
 * - **API ID**: `videoLoop`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type SmallMediaSliceVideoLoop = prismic.SharedSliceVariation<
  "videoLoop",
  Simplify<SmallMediaSliceVideoLoopPrimary>,
  never
>;

/**
 * Slice variation for *SmallMedia*
 */
type SmallMediaSliceVariation =
  | SmallMediaSliceDefault
  | SmallMediaSliceVideoLoop;

/**
 * SmallMedia Shared Slice
 *
 * - **API ID**: `small_media`
 * - **Description**: SmallMedia
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type SmallMediaSlice = prismic.SharedSlice<
  "small_media",
  SmallMediaSliceVariation
>;

/**
 * Primary content in *TextSlice → Default → Primary*
 */
export interface TextSliceSliceDefaultPrimary {
  /**
   * Text field in *TextSlice → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: text_slice.default.primary.text
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  text: prismic.RichTextField;
}

/**
 * Default variation for TextSlice Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type TextSliceSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<TextSliceSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *TextSlice*
 */
type TextSliceSliceVariation = TextSliceSliceDefault;

/**
 * TextSlice Shared Slice
 *
 * - **API ID**: `text_slice`
 * - **Description**: TextSlice
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type TextSliceSlice = prismic.SharedSlice<
  "text_slice",
  TextSliceSliceVariation
>;

/**
 * Primary content in *VideoPlayer → Default → Primary*
 */
export interface VideoPlayerSliceDefaultPrimary {
  /**
   * Video Placeholder Image field in *VideoPlayer → Default → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: video_player.default.primary.video_placeholder_image
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  video_placeholder_image: prismic.ImageField<never>;

  /**
   * Vimeo Video Link field in *VideoPlayer → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: video_player.default.primary.vimeo_video_link_new
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  vimeo_video_link_new: prismic.KeyTextField;

  /**
   * Caption field in *VideoPlayer → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: video_player.default.primary.caption
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  caption: prismic.RichTextField;

  /**
   * Bottom Margin field in *VideoPlayer → Default → Primary*
   *
   * - **Field Type**: Boolean
   * - **Placeholder**: *None*
   * - **Default Value**: false
   * - **API ID Path**: video_player.default.primary.bottom_margin
   * - **Documentation**: https://prismic.io/docs/field#boolean
   */
  bottom_margin: prismic.BooleanField;
}

/**
 * Default variation for VideoPlayer Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type VideoPlayerSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<VideoPlayerSliceDefaultPrimary>,
  never
>;

/**
 * Primary content in *VideoPlayer → Fullscreen → Primary*
 */
export interface VideoPlayerSliceFullscreenPrimary {
  /**
   * Video Placeholder Image field in *VideoPlayer → Fullscreen → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: video_player.fullscreen.primary.video_placeholder_image
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  video_placeholder_image: prismic.ImageField<never>;

  /**
   * Vimeo Video Link field in *VideoPlayer → Fullscreen → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: video_player.fullscreen.primary.vimeo_video_link_new
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  vimeo_video_link_new: prismic.KeyTextField;

  /**
   * Caption field in *VideoPlayer → Fullscreen → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: video_player.fullscreen.primary.caption
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  caption: prismic.RichTextField;

  /**
   * Bottom Margin field in *VideoPlayer → Fullscreen → Primary*
   *
   * - **Field Type**: Boolean
   * - **Placeholder**: *None*
   * - **Default Value**: false
   * - **API ID Path**: video_player.fullscreen.primary.bottom_margin
   * - **Documentation**: https://prismic.io/docs/field#boolean
   */
  bottom_margin: prismic.BooleanField;
}

/**
 * Fullscreen variation for VideoPlayer Slice
 *
 * - **API ID**: `fullscreen`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type VideoPlayerSliceFullscreen = prismic.SharedSliceVariation<
  "fullscreen",
  Simplify<VideoPlayerSliceFullscreenPrimary>,
  never
>;

/**
 * Slice variation for *VideoPlayer*
 */
type VideoPlayerSliceVariation =
  | VideoPlayerSliceDefault
  | VideoPlayerSliceFullscreen;

/**
 * VideoPlayer Shared Slice
 *
 * - **API ID**: `video_player`
 * - **Description**: VideoPlayer
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type VideoPlayerSlice = prismic.SharedSlice<
  "video_player",
  VideoPlayerSliceVariation
>;

declare module "@prismicio/client" {
  interface CreateClient {
    (
      repositoryNameOrEndpoint: string,
      options?: prismic.ClientConfig,
    ): prismic.Client<AllDocumentTypes>;
  }

  interface CreateWriteClient {
    (
      repositoryNameOrEndpoint: string,
      options: prismic.WriteClientConfig,
    ): prismic.WriteClient<AllDocumentTypes>;
  }

  interface CreateMigration {
    (): prismic.Migration<AllDocumentTypes>;
  }

  namespace Content {
    export type {
      AboutDocument,
      AboutDocumentData,
      AboutDocumentDataSlideshowItem,
      AboutDocumentDataWhatWeDoItem,
      AboutDocumentDataWhatSlideshowItem,
      AboutDocumentDataTeamListItem,
      ArchiveDocument,
      ArchiveDocumentData,
      ArchiveDocumentDataProjectsItem,
      CaseStudyDocument,
      CaseStudyDocumentData,
      CaseStudyDocumentDataGalleryThumbnailItem,
      CaseStudyDocumentDataClientItem,
      CaseStudyDocumentDataIndustryItem,
      CaseStudyDocumentDataSlices4Slice,
      ClientDocument,
      ClientDocumentData,
      ContactDocument,
      ContactDocumentData,
      GlobalDocument,
      GlobalDocumentData,
      HomeDocument,
      HomeDocumentData,
      HomeDocumentDataSlideshowItem,
      HomeDocumentDataSlices2Slice,
      HomeDocumentDataAboutSlideshowItem,
      IndustryDocument,
      IndustryDocumentData,
      MainMenuDocument,
      MainMenuDocumentData,
      MainMenuDocumentDataLinksItem,
      MobileMenuDocument,
      MobileMenuDocumentData,
      MobileMenuDocumentDataLinksItem,
      NewsDocument,
      NewsDocumentData,
      NewsLandingDocument,
      NewsLandingDocumentData,
      NewsLandingDocumentDataNewsItemsItem,
      WorkDocument,
      WorkDocumentData,
      WorkDocumentDataProjectsItem,
      AllDocumentTypes,
      AudioPlayerSlice,
      AudioPlayerSliceDefaultPrimary,
      AudioPlayerSliceVariation,
      AudioPlayerSliceDefault,
      DoubleMediaSlice,
      DoubleMediaSliceDefaultPrimary,
      DoubleMediaSliceVariation,
      DoubleMediaSliceDefault,
      LargeMediaSlice,
      LargeMediaSliceDefaultPrimary,
      LargeMediaSliceVideoPrimary,
      LargeMediaSliceVariation,
      LargeMediaSliceDefault,
      LargeMediaSliceVideo,
      MediumMediaSlice,
      MediumMediaSliceDefaultPrimary,
      MediumMediaSliceVideoPrimary,
      MediumMediaSliceVariation,
      MediumMediaSliceDefault,
      MediumMediaSliceVideo,
      ProjectSlice,
      ProjectSliceDefaultPrimaryMedia1Item,
      ProjectSliceDefaultPrimaryMedia2Item,
      ProjectSliceDefaultPrimaryMedia3Item,
      ProjectSliceDefaultPrimary,
      ProjectSliceVariation,
      ProjectSliceDefault,
      SmallGallerySlice,
      SmallGallerySliceDefaultPrimaryImagesItem,
      SmallGallerySliceDefaultPrimary,
      SmallGallerySliceVariation,
      SmallGallerySliceDefault,
      SmallMediaSlice,
      SmallMediaSliceDefaultPrimary,
      SmallMediaSliceVideoLoopPrimary,
      SmallMediaSliceVariation,
      SmallMediaSliceDefault,
      SmallMediaSliceVideoLoop,
      TextSliceSlice,
      TextSliceSliceDefaultPrimary,
      TextSliceSliceVariation,
      TextSliceSliceDefault,
      VideoPlayerSlice,
      VideoPlayerSliceDefaultPrimary,
      VideoPlayerSliceFullscreenPrimary,
      VideoPlayerSliceVariation,
      VideoPlayerSliceDefault,
      VideoPlayerSliceFullscreen,
    };
  }
}
