// Code generated by Slice Machine. DO NOT EDIT.

import { defineAsyncComponent } from "vue";
import { defineSliceZoneComponents } from "@prismicio/vue";

export const components = defineSliceZoneComponents({
  large_media: defineAsyncComponent(() => import("./LargeMedia/index.vue")),
  medium_media: defineAsyncComponent(() => import("./MediumMedia/index.vue")),
  small_gallery: defineAsyncComponent(() => import("./SmallGallery/index.vue")),
  small_media: defineAsyncComponent(() => import("./SmallMedia/index.vue")),
  text_slice: defineAsyncComponent(() => import("./TextSlice/index.vue")),
  video_player: defineAsyncComponent(() => import("./VideoPlayer/index.vue")),
});
