// Code generated by Slice Machine. DO NOT EDIT.

import { defineAsyncComponent } from "vue";
import { defineSliceZoneComponents } from "@prismicio/vue";

export const components = defineSliceZoneComponents({
  audio_player: defineAsyncComponent(() => import("./AudioPlayer/index.vue")),
  double_media: defineAsyncComponent(() => import("./DoubleMedia/index.vue")),
  large_media: defineAsyncComponent(() => import("./LargeMedia/index.vue")),
  medium_gallery: defineAsyncComponent(
    () => import("./MediumGallery/index.vue"),
  ),
  medium_media: defineAsyncComponent(() => import("./MediumMedia/index.vue")),
  project: defineAsyncComponent(() => import("./Project/index.vue")),
  small_gallery: defineAsyncComponent(() => import("./SmallGallery/index.vue")),
  small_media: defineAsyncComponent(() => import("./SmallMedia/index.vue")),
  text_slice: defineAsyncComponent(() => import("./TextSlice/index.vue")),
  video_player: defineAsyncComponent(() => import("./VideoPlayer/index.vue")),
});
